/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sujirour (https://sketchfab.com/sujirour)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chinese-rose-eaee5c918ab74563867f445569eb65bc
title: Chinese Rose
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    chinese_rose_small_chinese_rose_mat_0: THREE.Mesh
    chinese_rose_chinese_rose_mat_0: THREE.Mesh
  }
  materials: {
    chinese_rose_mat: THREE.MeshBasicMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.chinese_rose_small_chinese_rose_mat_0.geometry}
              material={nodes.chinese_rose_small_chinese_rose_mat_0.material}
            />
          </group>
          <group position={[0.2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.chinese_rose_chinese_rose_mat_0.geometry}
              material={nodes.chinese_rose_chinese_rose_mat_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
